# data_dir: ${data_dir}  # data_dir is specified in config.yaml
data_dir: "/sk3d/dataset/dragon/tis_right/rgb/undistorted/ambient@best"
cam_params: "/sk3d/addons/dragon/tis_right/rgb/mvsnet_input"
depth_dir: "/sk3d/addons/dragon/proj_depth/kinect_v2.undist@tis_right.undist"
gt_mesh: "/sk3d/dataset/dragon/stl/reconstruction/cleaned.ply"
# subdomain: "fusion"

name: "fusion_inference_dataset_sk3d"
img_res: [480, 640]
train_cameras: False
num_pixels: 5000
scan_id: "sk3d/dragon"
num_images: 300
skip_images: 10
sample_shift: 0

downsample_scale: 1.
downsample_mode: null # or sparse
train_batch_size: 1
eval_batch_size: 1
max_eval_imgs: 1
shuffle: True
num_workers: 0
first_k: 2
max_neighbor_images: 5

out_root: null

# for end-to-end
depth_scale: 1000.

confidence_level: 0